import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
export const metadata = {
  title: "Farrago",
  description: "Generated by Farrago",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <main className="m-0 font-sans text-base antialiased font-normal leading-default bg-gray-50 text-slate-500">
        <Sidebar />
        <main className="ease-soft-in-out xl:ml-68.5 relative h-full max-h-screen rounded-xl transition-all duration-200">
        <Navbar />
        {children}
        </main>
      </main>
  );
}
