import Sidebar from "@/components/Sidebar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="m-0 font-sans text-base antialiased font-normal leading-default bg-gray-50 text-slate-500">
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
